s = str(input())
s = s.lower()
s1 = s.split("u")
s1 = "".join(s1)
s1 = s1.split("e")
s1 = "".join(s1)
s1 = s1.split("o")
s1 = "".join(s1)
s1 = s1.split("a")
s1 = "".join(s1)
s1 = s1.split("i")
s1 = "".join(s1)
s1 = s1.split("y")
s1 = "".join(s1)
s2 = ".".join(s1)
print("."+s2)
